### ISSUE TITLE
Text letter spacing and line-height rules misunderstood

### ISSUE THREAD

**Issue by Arkkimaagi** [ygev/sketch-accessibility-assistant#4]
Thanks for the accessibility assistant, I wanted to take it for a spin as soon as I saw it!

Success Criterion 1.4.12 Text Spacing does not require that all text is set to be 0.12 * font-size letter spacing, but instead it requires that if an end user overrides your website settings to be 0.12 * font size, the interface should not hide content or overlap another content.

https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html

This is not something that can be checked in sketch as it does not "lay out" the interface automatically. And as such I consider this assistant to report accessibility wrong regarding this.

I'd remove this rule from this assistant as it does not check the WCAG success criterion 1.4.12 correctly.

Edit: I also noticed that the line-height rule has the same misunderstanding. It does not require you to have a line-height of ≥1.5, but requires you to have space for the end user to override your chosen line-height with at least 1.5 and not overlap other text on page. Same problem and recommendation regarding this rule in my mind.

**Comment by ygev** [comment]
Very good catch! Thank you for clearing this up. It did seem a little confusing to me when reading the Success Criteria, especially the 0.12 letter-spacing rule. I am removing these rules in 1.3.9. Please let me know if any other rules I add in the future misinterpret WCAG and other accessible practices. I always value feedback.
